#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

set_time_limit(0);
@ini_set("memory_limit","1G");




require(__DIR__ . '/vendor/autoload.php');

if ($_ENV['debug'])
{
    define('APPLICATION_ENV', 'dev');
}
else
{
    define('APPLICATION_ENV', 'prod');
}

defined('YII_DEBUG') or define('YII_DEBUG', $_ENV["debug"]);
defined('YII_ENV') or define('YII_ENV', APPLICATION_ENV);
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
